/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_qat_jni_CarbondataQatJNI */

#ifndef _Included_com_intel_qat_jni_CarbondataQatJNI
#define _Included_com_intel_qat_jni_CarbondataQatJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_qat_jni_CarbondataQatJNI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_qat_jni_CarbondataQatJNI_init
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_qat_jni_CarbondataQatJNI
 * Method:    compress
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_jni_CarbondataQatJNI_compress
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_intel_qat_jni_CarbondataQatJNI
 * Method:    decompress
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_jni_CarbondataQatJNI_decompress
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     com_intel_qat_jni_CarbondataQatJNI
 * Method:    maxCompressedLength
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_jni_CarbondataQatJNI_maxCompressedLength
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
